tests: check if fio is installed
Adds a quick "fio --version" check to make sure fio is installed.
While fio isn't required for ublk testing, many of the test suites
assume fio is installed.

The test output doesn't make it obvious that fio being missing is an
issue.

Before:

https://gist.github.com/mattysweeps/ebed18692821bdebce167dbfe2ce834d

After:

$ sudo make test T=null
make -C tests run T=null R=10 D=tests/tmp/
make[1]: Entering directory '/home/mattysweeps/src/github.com/ublk-org/ublksrv/tests'
./run_test.sh null 10 tests/tmp/
error: fio command could not be found
make[1]: *** [Makefile:492: run] Error 255
make[1]: Leaving directory '/home/mattysweeps/src/github.com/ublk-org/ublksrv/tests'
make: *** [Makefile:1627: test] Error 2