ublksrv: fix build failure on gcc version 11.2.1
Fix the following issue in case that 'gcc version 11.2.1' is used.

tgt_null.c: In function 'int null_init_tgt(ublksrv_dev*, int, int, char**)':
tgt_null.c:13:9: error: C99 designator 'name' outside aggregate initializer
   13 |         };
      |         ^

Signed-off-by: Ming Lei <tom.leiming@gmail.com>