missing <limits.h> header
building on my Debian 11 system with gcc I get these errors:

      CXX      ublk-tgt_loop.o
    tgt_loop.cpp: In function ‘int loop_init_tgt(ublksrv_dev*, int, int, char**)’:
    tgt_loop.cpp:123:27: error: ‘UINT_MAX’ was not declared in this scope
      123 |    .max_discard_sectors = UINT_MAX >> 9,
          |                           ^~~~~~~~
    tgt_loop.cpp:8:1: note: ‘UINT_MAX’ is defined in header ‘<climits>’; did you forget to ‘#include <climits>’?
        7 | #include "ublksrv_tgt.h"
      +++ |+#include <climits>
        8 |

Adding the <limits.h> header to ublksrv_tgt.h as suggested by Ming Lei.

Signed-off-by: Bart Trojanowski <bart@jukie.net>